#steps:
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['functions', 'deploy', '[YOUR_DEPLOYED_FUNCTION_NAME]', '[YOUR_FUNCTION_TRIGGER]', '--runtime', '[YOUR_RUNTIME]', '--entry-point', '[YOUR_FUNCTION_NAME_IN_CODE]']
#  dir: 'function/dir/from/repo/root'

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'helloworld', '--trigger-http', '--runtime', 'nodejs12', '--entry-point', 'helloworld']
  dir: './helloworld'




