#hello changes
steps:
- name: 'gcr.io/cloud-builders/npm'
  dir: './helloworld/functions'
  args: ['install']
  
- name: 'gcr.io/general-277014/firebase'
  args: [ 'deploy', '--only', 'functions']
  dir: './helloworld'

- name: 'gcr.io/cloud-builders/npm'
  dir: './helloworld2/functions'
  args: ['install']

- name: 'gcr.io/general-277014/firebase'
  args: [ 'deploy', '--only', 'functions']
  dir: './helloworld2'
